version: '3.4'

services: 
  cumplidos_crud_api:

    image: golang:1.15-alpine
    container_name: ${SERVICE_NAME}
    volumes:
      - go_src:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    environment:
      - GO111MODULE=on
    env_file: 
      - .env
    ports: 
      - "${CUMPLIDOS_CRUD_API_ADMIN_PORT}:${CUMPLIDOS_CRUD_API_ADMIN_PORT}"  
    working_dir: /go/src
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -u github.com/beego/bee ;go get -v -u ./...; pwd;go mod init; bee run -downdoc=true -gendoc=true'

  data_base:
    container_name: ${BD_NAME}
    image: postgres:10.15-alpine
    volumes: 
        - postgres_data:/var/lib/postgresql/data
    ports: 
        - "5434:5432"        
    env_file: 
        - .env
    networks: 
        - back_end



volumes:
  go_src:
  postgres_data:
networks: 
  back_end:
    external: true